# Generated by Django 5.1.6 on 2025-03-27 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Genre', models.CharField(max_length=20)),
                ('Hero', models.CharField(max_length=20)),
                ('Run', models.FloatField()),
                ('Rating', models.IntegerField()),
            ],
        ),
    ]
